version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: dongpaidi-postgres
    environment:
      POSTGRES_DB: dongpaidi_db
      POSTGRES_USER: dongpaidi_user
      POSTGRES_PASSWORD: dongpaidi_password_2024
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - dongpaidi-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dongpaidi_user -d dongpaidi_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: dongpaidi-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dongpaidi-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  dongpaidi-network:
    driver: bridge
